// scripts/CheckStructure.ts

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import fg from 'fast-glob';

// ✅ รองรับ __dirname ใน ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ✅ กำหนด Root และ Output file
const ROOT_DIR = path.resolve(__dirname, '../src');
const OUTPUT_FILE = path.resolve(__dirname, '../STRUCTURE.md');

// ✅ ฟังก์ชันสำหรับสร้าง indentation
function indent(level: number): string {
  return '  '.repeat(level);
}

// ✅ แปลง paths ให้เป็น tree แบบ markdown
function formatTree(entries: string[], baseDir: string): string {
  const tree: string[] = [];
  const seen = new Set<string>();

  for (const entry of entries) {
    const relPath = path.relative(baseDir, entry);
    const parts = relPath.split(path.sep);

    let currentPath = '';
    parts.forEach((part, index) => {
      currentPath = path.join(currentPath, part);
      const key = `${index}-${currentPath}`;
      if (seen.has(key)) return;

      seen.add(key);
      const isFile = part.includes('.') && index === parts.length - 1;
      const line = `${indent(index)}- ${part}${isFile ? '' : '/'}`;
      tree.push(line);
    });
  }

  return tree.join('\n');
}

// ✅ main: Generate STRUCTURE.md
async function main() {
  try {
    const entries = await fg(['**/*.{ts,tsx}'], {
      cwd: ROOT_DIR,
      onlyFiles: true,
      dot: false,
      absolute: true,
    });

    const header = [
      '# 📁 Project Source Structure (`src/`)',
      '',
      '```text',
    ].join('\n');

    const footer = [
      '```',
      '',
      '> ✅ Generated by `scripts/CheckStructure.ts`',
      '> ℹ️ NOTE: โค้ดทั้งหมดทำงานภายใต้แนวทาง Dev to Dev แบบเข้มงวด เน้นการทำงานร่วมกัน ตรวจสอบโครงสร้าง project ให้สมบูรณ์และเป็นระเบียบ หลีกเลี่ยงการ generate หรือแตกไฟล์นอกคำกำหนดเส้นทางกำหนดเราเตอร์ให้ถูกต้องโค้ดทุกตัวที่ส่งให้คือโค้ดที่ใช้ปัจจุบันตรวจสอบแก้ไข format code ส่งกลับ เก็บรายละเอียดต่างๆให้โค้ดออกมาสมบูรณ์ในการเขียนเป็นรูปแบบตามละเอียดโค้ดที่ให้ไปใช้เทคนิคในการเขียน Code ให้ professional ที่สุดสั่ง'
    ].join('\n');

    const body = formatTree(entries, ROOT_DIR);
    const output = [header, body, footer].join('\n');

    fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
    console.log(`✅ STRUCTURE.md generated at: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error('❌ Error generating structure:', err);
    process.exit(1);
  }
}

main();